pipeline{
    agent{
        label 'linux-agent'
    }
    stages{
        stage ('Hello'){
            steps{
                echo "Hello, Jenkins Pipeline!"
            }
        }
    }
    post{
        always{
            echo "pipeline execution completed"
        }
        success{
            echo "pipline executed successfully"
        }
        failure{
            echo "pipeline execution failed"
        }
    }
}
