pipeline{
    agent{
        label 'linux-agent'
    }
    stages{
        stage ('workspace'){
            steps{
                echo "Workspace Path: ${env.WORKSPACE}"
            }
        }
    }
    
    post{
        always{
            echo "pipeline execution completed"
        }
        success{
            echo "pipline executed successfully"
        }
        failure{
            echo "pipeline execution failed"
        }
    }
}
